(cl:in-package krssg_ssl_msgs-msg)
(cl:export '(PACKET_TIMESTAMP-VAL
          PACKET_TIMESTAMP
          STAGE-VAL
          STAGE
          STAGE_TIME_LEFT-VAL
          STAGE_TIME_LEFT
          COMMAND-VAL
          COMMAND
          COMMAND_COUNTER-VAL
          COMMAND_COUNTER
          COMMAND_TIMESTAMP-VAL
          COMMAND_TIMESTAMP
          B_NAME-VAL
          B_NAME
          B_SCORE-VAL
          B_SCORE
          B_RED_CARDS-VAL
          B_RED_CARDS
          B_YELLOW_CARDS-VAL
          B_YELLOW_CARDS
          B_TIMEOUTS-VAL
          B_TIMEOUTS
          B_TIMEOUT_TIME-VAL
          B_TIMEOUT_TIME
          B_GOALIE-VAL
          B_GOALIE
          Y_NAME-VAL
          Y_NAME
          Y_SCORE-VAL
          Y_SCORE
          Y_RED_CARDS-VAL
          Y_RED_CARDS
          Y_YELLOW_CARDS-VAL
          Y_YELLOW_CARDS
          Y_TIMEOUTS-VAL
          Y_TIMEOUTS
          Y_TIMEOUT_TIME-VAL
          Y_TIMEOUT_TIME
          Y_GOALIE-VAL
          Y_GOALIE
          Y_CARD_TIMES-VAL
          Y_CARD_TIMES
          B_CARD_TIMES-VAL
          B_CARD_TIMES
))