(cl:in-package krssg_ssl_msgs-msg)
(cl:export '(ISTEAMYELLOW-VAL
          ISTEAMYELLOW
          FRAME_NUMBER-VAL
          FRAME_NUMBER
          T_CAPTURE-VAL
          T_CAPTURE
          T_SENT-VAL
          T_SENT
          BALLPOS-VAL
          BALLPOS
          BALLVEL-VAL
          BALLVEL
          AWAYPOS-VAL
          AWAYPOS
          HOMEPOS-VAL
          HOMEPOS
          AWAYVEL-VAL
          AWAYVEL
          HOMEVEL-VAL
          HOMEVEL
          BALLDETECTED-VAL
          BALLDETECTED
          HOMEDETECTED-VAL
          HOMEDETECTED
          AWAYDETECTED-VAL
          AWAYDETECTED
          OUR_BOT_CLOSEST_TO_BALL-VAL
          OUR_BOT_CLOSEST_TO_BALL
          OPP_BOT_CLOSEST_TO_BALL-VAL
          OPP_BOT_CLOSEST_TO_BALL
          OUR_GOALIE-VAL
          OUR_GOALIE
          OPP_GOALIE-VAL
          OPP_GOALIE
          OPP_BOT_MARKING_OUR_ATTACKER-VAL
          OPP_BOT_MARKING_OUR_ATTACKER
          BALL_AT_CORNERS-VAL
          BALL_AT_CORNERS
          BALL_IN_OUR_HALF-VAL
          BALL_IN_OUR_HALF
          BALL_IN_OUR_POSSESSION-VAL
          BALL_IN_OUR_POSSESSION
))