// Generated by gencpp from file krssg_ssl_msgs/gr_Replacement.msg
// DO NOT EDIT!


#ifndef KRSSG_SSL_MSGS_MESSAGE_GR_REPLACEMENT_H
#define KRSSG_SSL_MSGS_MESSAGE_GR_REPLACEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <krssg_ssl_msgs/gr_BallReplacement.h>
#include <krssg_ssl_msgs/gr_RobotReplacement.h>

namespace krssg_ssl_msgs
{
template <class ContainerAllocator>
struct gr_Replacement_
{
  typedef gr_Replacement_<ContainerAllocator> Type;

  gr_Replacement_()
    : ball()
    , robots()  {
    }
  gr_Replacement_(const ContainerAllocator& _alloc)
    : ball(_alloc)
    , robots(_alloc)  {
  (void)_alloc;
    }



   typedef  ::krssg_ssl_msgs::gr_BallReplacement_<ContainerAllocator>  _ball_type;
  _ball_type ball;

   typedef  ::krssg_ssl_msgs::gr_RobotReplacement_<ContainerAllocator>  _robots_type;
  _robots_type robots;




  typedef boost::shared_ptr< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> const> ConstPtr;

}; // struct gr_Replacement_

typedef ::krssg_ssl_msgs::gr_Replacement_<std::allocator<void> > gr_Replacement;

typedef boost::shared_ptr< ::krssg_ssl_msgs::gr_Replacement > gr_ReplacementPtr;
typedef boost::shared_ptr< ::krssg_ssl_msgs::gr_Replacement const> gr_ReplacementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace krssg_ssl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'krssg_ssl_msgs': ['/home/ss/robocup/src/krssg_ssl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63f6045fad0d38b32afdf3f8ecc35d5c";
  }

  static const char* value(const ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63f6045fad0d38b3ULL;
  static const uint64_t static_value2 = 0x2afdf3f8ecc35d5cULL;
};

template<class ContainerAllocator>
struct DataType< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krssg_ssl_msgs/gr_Replacement";
  }

  static const char* value(const ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gr_BallReplacement ball  \n\
gr_RobotReplacement robots  \n\
\n\
\n\
================================================================================\n\
MSG: krssg_ssl_msgs/gr_BallReplacement\n\
float64 x \n\
float64 y \n\
float64 vx \n\
float64 vy \n\
\n\
\n\
================================================================================\n\
MSG: krssg_ssl_msgs/gr_RobotReplacement\n\
float64 x \n\
float64 y \n\
float64 dir \n\
uint32 id \n\
bool yellowteam \n\
";
  }

  static const char* value(const ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ball);
      stream.next(m.robots);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct gr_Replacement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krssg_ssl_msgs::gr_Replacement_<ContainerAllocator>& v)
  {
    s << indent << "ball: ";
    s << std::endl;
    Printer< ::krssg_ssl_msgs::gr_BallReplacement_<ContainerAllocator> >::stream(s, indent + "  ", v.ball);
    s << indent << "robots: ";
    s << std::endl;
    Printer< ::krssg_ssl_msgs::gr_RobotReplacement_<ContainerAllocator> >::stream(s, indent + "  ", v.robots);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSSG_SSL_MSGS_MESSAGE_GR_REPLACEMENT_H
