// Generated by gencpp from file krssg_ssl_msgs/SSL_DetectionBall.msg
// DO NOT EDIT!


#ifndef KRSSG_SSL_MSGS_MESSAGE_SSL_DETECTIONBALL_H
#define KRSSG_SSL_MSGS_MESSAGE_SSL_DETECTIONBALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krssg_ssl_msgs
{
template <class ContainerAllocator>
struct SSL_DetectionBall_
{
  typedef SSL_DetectionBall_<ContainerAllocator> Type;

  SSL_DetectionBall_()
    : confidence(0.0)
    , area(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , pixel_x(0.0)
    , pixel_y(0.0)  {
    }
  SSL_DetectionBall_(const ContainerAllocator& _alloc)
    : confidence(0.0)
    , area(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , pixel_x(0.0)
    , pixel_y(0.0)  {
  (void)_alloc;
    }



   typedef double _confidence_type;
  _confidence_type confidence;

   typedef uint32_t _area_type;
  _area_type area;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _pixel_x_type;
  _pixel_x_type pixel_x;

   typedef double _pixel_y_type;
  _pixel_y_type pixel_y;




  typedef boost::shared_ptr< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> const> ConstPtr;

}; // struct SSL_DetectionBall_

typedef ::krssg_ssl_msgs::SSL_DetectionBall_<std::allocator<void> > SSL_DetectionBall;

typedef boost::shared_ptr< ::krssg_ssl_msgs::SSL_DetectionBall > SSL_DetectionBallPtr;
typedef boost::shared_ptr< ::krssg_ssl_msgs::SSL_DetectionBall const> SSL_DetectionBallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace krssg_ssl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'krssg_ssl_msgs': ['/home/aif/ssl/americast/src/krssg_ssl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da53de0da1e4e3e19a8eddfe942e84c8";
  }

  static const char* value(const ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda53de0da1e4e3e1ULL;
  static const uint64_t static_value2 = 0x9a8eddfe942e84c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krssg_ssl_msgs/SSL_DetectionBall";
  }

  static const char* value(const ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64  confidence \n\
uint32 area      \n\
float64  x         \n\
float64  y          \n\
float64  z          \n\
float64  pixel_x    \n\
float64  pixel_y    \n\
";
  }

  static const char* value(const ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confidence);
      stream.next(m.area);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.pixel_x);
      stream.next(m.pixel_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SSL_DetectionBall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krssg_ssl_msgs::SSL_DetectionBall_<ContainerAllocator>& v)
  {
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "area: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.area);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "pixel_x: ";
    Printer<double>::stream(s, indent + "  ", v.pixel_x);
    s << indent << "pixel_y: ";
    Printer<double>::stream(s, indent + "  ", v.pixel_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSSG_SSL_MSGS_MESSAGE_SSL_DETECTIONBALL_H
