// Generated by gencpp from file krssg_ssl_msgs/TacticPacket.msg
// DO NOT EDIT!


#ifndef KRSSG_SSL_MSGS_MESSAGE_TACTICPACKET_H
#define KRSSG_SSL_MSGS_MESSAGE_TACTICPACKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krssg_ssl_msgs
{
template <class ContainerAllocator>
struct TacticPacket_
{
  typedef TacticPacket_<ContainerAllocator> Type;

  TacticPacket_()
    : tID()
    , tParamJSON()  {
    }
  TacticPacket_(const ContainerAllocator& _alloc)
    : tID(_alloc)
    , tParamJSON(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tID_type;
  _tID_type tID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tParamJSON_type;
  _tParamJSON_type tParamJSON;




  typedef boost::shared_ptr< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> const> ConstPtr;

}; // struct TacticPacket_

typedef ::krssg_ssl_msgs::TacticPacket_<std::allocator<void> > TacticPacket;

typedef boost::shared_ptr< ::krssg_ssl_msgs::TacticPacket > TacticPacketPtr;
typedef boost::shared_ptr< ::krssg_ssl_msgs::TacticPacket const> TacticPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace krssg_ssl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'krssg_ssl_msgs': ['/home/ss/robocup/src/krssg_ssl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa10ebbde9705347694b0dec25403";
  }

  static const char* value(const ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa10ebbde9705ULL;
  static const uint64_t static_value2 = 0x347694b0dec25403ULL;
};

template<class ContainerAllocator>
struct DataType< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krssg_ssl_msgs/TacticPacket";
  }

  static const char* value(const ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message for passing tactic name and tactic param from play -> robot\n\
string tID\n\
string tParamJSON\n\
";
  }

  static const char* value(const ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tID);
      stream.next(m.tParamJSON);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TacticPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krssg_ssl_msgs::TacticPacket_<ContainerAllocator>& v)
  {
    s << indent << "tID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tID);
    s << indent << "tParamJSON: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tParamJSON);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSSG_SSL_MSGS_MESSAGE_TACTICPACKET_H
