// Generated by gencpp from file plays_py/role_to_playRequest.msg
// DO NOT EDIT!


#ifndef PLAYS_PY_MESSAGE_ROLE_TO_PLAYREQUEST_H
#define PLAYS_PY_MESSAGE_ROLE_TO_PLAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plays_py
{
template <class ContainerAllocator>
struct role_to_playRequest_
{
  typedef role_to_playRequest_<ContainerAllocator> Type;

  role_to_playRequest_()
    : ping(false)  {
    }
  role_to_playRequest_(const ContainerAllocator& _alloc)
    : ping(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ping_type;
  _ping_type ping;




  typedef boost::shared_ptr< ::plays_py::role_to_playRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plays_py::role_to_playRequest_<ContainerAllocator> const> ConstPtr;

}; // struct role_to_playRequest_

typedef ::plays_py::role_to_playRequest_<std::allocator<void> > role_to_playRequest;

typedef boost::shared_ptr< ::plays_py::role_to_playRequest > role_to_playRequestPtr;
typedef boost::shared_ptr< ::plays_py::role_to_playRequest const> role_to_playRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plays_py::role_to_playRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plays_py::role_to_playRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plays_py

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plays_py::role_to_playRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plays_py::role_to_playRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plays_py::role_to_playRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plays_py::role_to_playRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plays_py::role_to_playRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plays_py::role_to_playRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plays_py::role_to_playRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a5baecc88251a03a5502608e8b4b241";
  }

  static const char* value(const ::plays_py::role_to_playRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a5baecc88251a03ULL;
  static const uint64_t static_value2 = 0xa5502608e8b4b241ULL;
};

template<class ContainerAllocator>
struct DataType< ::plays_py::role_to_playRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plays_py/role_to_playRequest";
  }

  static const char* value(const ::plays_py::role_to_playRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plays_py::role_to_playRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ping\n\
";
  }

  static const char* value(const ::plays_py::role_to_playRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plays_py::role_to_playRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ping);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct role_to_playRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plays_py::role_to_playRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plays_py::role_to_playRequest_<ContainerAllocator>& v)
  {
    s << indent << "ping: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ping);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAYS_PY_MESSAGE_ROLE_TO_PLAYREQUEST_H
