# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from krssg_ssl_msgs/gr_Replacement.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import krssg_ssl_msgs.msg

class gr_Replacement(genpy.Message):
  _md5sum = "63f6045fad0d38b32afdf3f8ecc35d5c"
  _type = "krssg_ssl_msgs/gr_Replacement"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """gr_BallReplacement ball  
gr_RobotReplacement robots  


================================================================================
MSG: krssg_ssl_msgs/gr_BallReplacement
float64 x 
float64 y 
float64 vx 
float64 vy 


================================================================================
MSG: krssg_ssl_msgs/gr_RobotReplacement
float64 x 
float64 y 
float64 dir 
uint32 id 
bool yellowteam 
"""
  __slots__ = ['ball','robots']
  _slot_types = ['krssg_ssl_msgs/gr_BallReplacement','krssg_ssl_msgs/gr_RobotReplacement']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ball,robots

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gr_Replacement, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ball is None:
        self.ball = krssg_ssl_msgs.msg.gr_BallReplacement()
      if self.robots is None:
        self.robots = krssg_ssl_msgs.msg.gr_RobotReplacement()
    else:
      self.ball = krssg_ssl_msgs.msg.gr_BallReplacement()
      self.robots = krssg_ssl_msgs.msg.gr_RobotReplacement()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_7dIB.pack(_x.ball.x, _x.ball.y, _x.ball.vx, _x.ball.vy, _x.robots.x, _x.robots.y, _x.robots.dir, _x.robots.id, _x.robots.yellowteam))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ball is None:
        self.ball = krssg_ssl_msgs.msg.gr_BallReplacement()
      if self.robots is None:
        self.robots = krssg_ssl_msgs.msg.gr_RobotReplacement()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.ball.x, _x.ball.y, _x.ball.vx, _x.ball.vy, _x.robots.x, _x.robots.y, _x.robots.dir, _x.robots.id, _x.robots.yellowteam,) = _struct_7dIB.unpack(str[start:end])
      self.robots.yellowteam = bool(self.robots.yellowteam)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_7dIB.pack(_x.ball.x, _x.ball.y, _x.ball.vx, _x.ball.vy, _x.robots.x, _x.robots.y, _x.robots.dir, _x.robots.id, _x.robots.yellowteam))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ball is None:
        self.ball = krssg_ssl_msgs.msg.gr_BallReplacement()
      if self.robots is None:
        self.robots = krssg_ssl_msgs.msg.gr_RobotReplacement()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.ball.x, _x.ball.y, _x.ball.vx, _x.ball.vy, _x.robots.x, _x.robots.y, _x.robots.dir, _x.robots.id, _x.robots.yellowteam,) = _struct_7dIB.unpack(str[start:end])
      self.robots.yellowteam = bool(self.robots.yellowteam)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7dIB = struct.Struct("<7dIB")
